name = "2027"
compatibility_date = "2025-10-22"
pages_build_output_dir = "dist"

# توحيد جميع KV Bindings على MMS_CACHE
# جميع المفاتيح تشير الآن إلى نفس KV namespace لتوحيد البيانات ومنع التعطل

[[kv_namespaces]]
binding = "KV_ADMIN"
id = "1d3d4e6c12174b7797b356234794e7e5"  # MMS_CACHE

[[kv_namespaces]]
binding = "KV_PINS"
id = "1d3d4e6c12174b7797b356234794e7e5"  # MMS_CACHE

[[kv_namespaces]]
binding = "KV_QUEUES"
id = "1d3d4e6c12174b7797b356234794e7e5"  # MMS_CACHE

[[kv_namespaces]]
binding = "KV_EVENTS"
id = "1d3d4e6c12174b7797b356234794e7e5"  # MMS_CACHE

[[kv_namespaces]]
binding = "KV_LOCKS"
id = "1d3d4e6c12174b7797b356234794e7e5"  # MMS_CACHE

[[kv_namespaces]]
binding = "KV_CACHE"
id = "1d3d4e6c12174b7797b356234794e7e5"  # MMS_CACHE

[vars]
TIMEZONE = "Asia/Qatar"
# Secrets (PIN_SECRET, JWT_SECRET, NOTIFY_KEY) are stored in:
# - Local development: .dev.vars file (not committed to git)
# - Production: Cloudflare Dashboard → Settings → Variables and Secrets

# CRON Triggers (Scheduled Events)
# Note: CRON triggers are configured in Cloudflare Dashboard for Pages Projects
# These are documented here for reference:
# - "0 0 * * *" (00:00 Qatar time) - Reset daily PINs
# - "*/1 * * * *" (Every minute) - Notify poller
# - "59 23 * * *" (23:59 Qatar time) - Daily backup and reports

