name = "mms-api-proxy"
main = "src/index.ts"
compatibility_date = "2025-10-01"

# قم بتحديث zone_name بحسب نطاقك على Cloudflare
routes = [
  { pattern = "api.mmc-mms.com/*", zone_name = "mmc-mms.com" },
  { pattern = "mmc-mms.com/api/*", zone_name = "mmc-mms.com" }
]

[triggers]
# تشغّل الـ Worker كل 10 دقائق (للفحص الدوري/التسخين)
crons = ["*/10 * * * *"]

[vars]
# لا تضع أسرار هنا؛ استخدم wrangler secret
# SITE_ORIGIN يفضّل وضعه هنا لأنه غير سرّي
SITE_ORIGIN = "https://mmc-mms.com"

# مسارات بديلة للباكند (غير سرّية إن كانت نطاقات عامة)
# BACKEND_ORIGIN يظل كـ secret ويتم تحديثه تلقائيًا بواسطة auto-origin-switcher.js
PRIMARY_ORIGIN = "https://app.mmc-mms.com"
SECONDARY_ORIGIN = "https://api.mmc-mms.com"
# حدّث قيمة workers.dev أدناه وفق حسابك في Cloudflare
FALLBACK_ORIGIN = "https://mms-api-proxy.<account>.workers.dev"

# لتمكين KV للـ Rate Limit، أنشئ namespace وباعد ربطه هنا
# [kv_namespaces]
# binding = "RATE_LIMIT_KV"
# id = "<KV_ID>"
# preview_id = "<KV_PREVIEW_ID>"

[observability]
logs = { enabled = true }
